const express=require('express');const db=require('../database/init');const {requireAuth}=require('../middleware/auth');const router=express.Router();
const norm=v=>v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:null;
const list=v=>{const a=Array.isArray(v)?v:String(v??'').split(',');return [...new Set(a.flatMap(x=>String(x).split(',')).map(x=>x.trim()).filter(x=>x&&x!=='__ALL__'))]};
const addIn=(w,p,col,vals)=>{if(!vals.length)return w;w+=` AND ${col} IN (${vals.map(()=>'?').join(',')})`;p.push(...vals);return w};
function base(req,p,o){let w=`sd.stage='الحضور' AND e.role='employee'`;if(req.user.role!=='admin'){w+=' AND e.id=?';p.push(Number(req.user.id))}if(o.from){w+=' AND sd.entry_date>=?';p.push(o.from)}if(o.to){w+=' AND sd.entry_date<=?';p.push(o.to)}w=addIn(w,p,"COALESCE(e.company,'')",o.company||[]);w=addIn(w,p,"COALESCE(e.department,'')",o.department||[]);w=addIn(w,p,"COALESCE(e.shift,'')",o.shift||[]);if(o.search){w+=' AND (CAST(e.id AS TEXT) LIKE ? OR e.name LIKE ?)';const q=`%${o.search}%`;p.push(q,q)}return w}
const status=(values,a='sd')=>{const ss=list(values);if(!ss.length)return'';const present=`(${a}.value_num IN (0.5,1,1.5))`,casual=`(${a}.value_num IS NOT NULL AND ${a}.value_num=0)`,permission=`TRIM(COALESCE(${a}.value_text,''))='ا'`,unauthorized=`TRIM(COALESCE(${a}.value_text,''))='ب'`,medical=`TRIM(COALESCE(${a}.value_text,''))='م'`;const parts=ss.map(s=>s==='present'?present:s==='casual'?casual:s==='permission'?permission:s==='unauthorized'?unauthorized:s==='medical'?medical:s==='absent'?`(${casual} OR ${permission} OR ${unauthorized} OR ${medical})`:null).filter(Boolean);return parts.length?` AND (${parts.join(' OR ')})`:''};
router.get('/meta',requireAuth,async (req,res)=>{const own=req.user.role==='admin'?'':` AND id=${Number(req.user.id)}`;const dates=(await db.prepare(`SELECT DISTINCT entry_date FROM stage_daily WHERE stage='الحضور' ORDER BY entry_date`).all()).map(r=>r.entry_date);const companies=(await db.prepare(`SELECT DISTINCT COALESCE(company,'') v FROM employees WHERE role='employee'${own} ORDER BY v`).all()).map(r=>r.v).filter(Boolean);const departments=(await db.prepare(`SELECT DISTINCT COALESCE(department,'') v FROM employees WHERE role='employee'${own} ORDER BY v`).all()).map(r=>r.v).filter(Boolean);const shifts=(await db.prepare(`SELECT DISTINCT COALESCE(shift,'') v FROM employees WHERE role='employee'${own} ORDER BY v`).all()).map(r=>r.v).filter(Boolean);res.json({dates,companies,departments,shifts})});
router.get('/',requireAuth,async (req,res)=>{let from=norm(req.query.from),to=norm(req.query.to);if(req.query.from&&!from)return res.status(400).json({error:'صيغة تاريخ البداية غير صحيحة.'});if(req.query.to&&!to)return res.status(400).json({error:'صيغة تاريخ النهاية غير صحيحة.'});if(from&&to&&from>to)return res.status(400).json({error:'تاريخ البداية يجب أن يسبق تاريخ النهاية.'});const dr=(await db.prepare(`SELECT MIN(entry_date) min,MAX(entry_date) max FROM stage_daily WHERE stage='الحضور'`).get());from=from||dr.min;to=to||dr.max;const o={from,to,company:list(req.query.company),department:list(req.query.department),shift:list(req.query.shift),search:req.query.search?String(req.query.search).trim():null},st=list(req.query.status);
const ep=[];let ew=`WHERE role='employee'`;if(req.user.role!=='admin'){ew+=' AND id=?';ep.push(Number(req.user.id))}for(const [col,key] of [['company','company'],['department','department'],['shift','shift']])ew=addIn(ew,ep,`COALESCE(${col},'')`,o[key]||[]);if(o.search){ew+=' AND (CAST(id AS TEXT) LIKE ? OR name LIKE ?)';const q=`%${o.search}%`;ep.push(q,q)}const employeeCount=Number((await db.prepare(`SELECT COUNT(*) c FROM employees ${ew}`).get(...ep)).c||0);
const present=`(sd.value_num IN (0.5,1,1.5))`,casual=`(sd.value_num IS NOT NULL AND sd.value_num=0)`,permissionCode=`TRIM(COALESCE(sd.value_text,''))='ا'`,unauth=`TRIM(COALESCE(sd.value_text,''))='ب'`,medical=`TRIM(COALESCE(sd.value_text,''))='م'`;const p=[];let w=base(req,p,o)+status(st);const t=(await db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN ${present} THEN sd.value_num ELSE 0 END) present,SUM(CASE WHEN ${casual} OR ${permissionCode} OR ${unauth} OR ${medical} THEN 1 ELSE 0 END) absent,SUM(CASE WHEN ${casual} THEN 1 ELSE 0 END) casual,SUM(CASE WHEN ${permissionCode} THEN 1 ELSE 0 END) permission,SUM(CASE WHEN ${unauth} THEN 1 ELSE 0 END) unauthorized,SUM(CASE WHEN ${medical} THEN 1 ELSE 0 END) medical FROM stage_daily sd JOIN employees e ON e.id=sd.employee_id WHERE ${w}`).get(...p));const total=Number(t.total||0),pres=Number(t.present||0),adjustedPresent=pres,adjustedTotal=total;
function grouped(extra=''){const q=[];return{w:base(req,q,o)+status(st)+extra,p:q}}
const cq=grouped();const companies=(await db.prepare(`SELECT CASE WHEN UPPER(TRIM(COALESCE(e.company,''))) LIKE '%SMART%' OR UPPER(TRIM(COALESCE(e.company,'')))='SB' THEN 'SMART BUSINESS' WHEN UPPER(TRIM(COALESCE(e.company,''))) LIKE '%BRAVOS%' THEN 'BRAVOS' ELSE 'أخرى' END name,COUNT(*) total,SUM(CASE WHEN ${present} THEN sd.value_num ELSE 0 END) present,SUM(CASE WHEN ${casual} OR ${permissionCode} OR ${unauth} OR ${medical} THEN 1 ELSE 0 END) absent,SUM(CASE WHEN ${present} AND e.education='خريج' THEN sd.value_num ELSE 0 END) graduate_present,SUM(CASE WHEN NOT ${present} AND e.education='خريج' THEN 1 ELSE 0 END) graduate_absent,SUM(CASE WHEN ${present} AND e.education='طالب' THEN sd.value_num ELSE 0 END) student_present,SUM(CASE WHEN NOT ${present} AND e.education='طالب' THEN 1 ELSE 0 END) student_absent,SUM(CASE WHEN ${casual} THEN 1 ELSE 0 END) casual,SUM(CASE WHEN ${permissionCode} THEN 1 ELSE 0 END) permission,SUM(CASE WHEN ${unauth} THEN 1 ELSE 0 END) unauthorized,SUM(CASE WHEN ${medical} THEN 1 ELSE 0 END) medical FROM stage_daily sd JOIN employees e ON e.id=sd.employee_id LEFT JOIN employee_summary es ON es.employee_id=e.id WHERE ${cq.w} GROUP BY 1 ORDER BY total DESC`).all(...cq.p)).map(r=>{const pp=+r.present||0,tt=+r.total||0;return{...r,total:tt,present:pp,absent:+r.absent||0,graduate_present:+r.graduate_present||0,graduate_absent:+r.graduate_absent||0,student_present:+r.student_present||0,student_absent:+r.student_absent||0,casual:+r.casual||0,permission:+r.permission||0,unauthorized:+r.unauthorized||0,medical:+r.medical||0,attendance_rate:tt?pp/tt*100:0}});
const cep=[];let cew=`WHERE role='employee'`;if(req.user.role!=='admin'){cew+=' AND id=?';cep.push(Number(req.user.id))}for(const [col,key] of [['company','company'],['department','department'],['shift','shift']])cew=addIn(cew,cep,`COALESCE(${col},'')`,o[key]||[]);if(o.search){cew+=' AND (CAST(id AS TEXT) LIKE ? OR name LIKE ?)';const q=`%${o.search}%`;cep.push(q,q)}const ce=(await db.prepare(`SELECT CASE WHEN UPPER(TRIM(COALESCE(company,''))) LIKE '%SMART%' OR UPPER(TRIM(COALESCE(company,'')))='SB' THEN 'SMART BUSINESS' WHEN UPPER(TRIM(COALESCE(company,''))) LIKE '%BRAVOS%' THEN 'BRAVOS' ELSE 'أخرى' END name,COUNT(*) employee_count FROM employees ${cew} GROUP BY 1`).all(...cep));const cem=Object.fromEntries(ce.map(r=>[r.name,+r.employee_count||0]));companies.forEach(r=>r.employee_count=cem[r.name]||0);
const sq=grouped();const sr=(await db.prepare(`SELECT COALESCE(NULLIF(TRIM(e.department),''),'غير محدد') stage,CASE WHEN UPPER(TRIM(COALESCE(e.company,''))) LIKE '%SMART%' OR UPPER(TRIM(COALESCE(e.company,'')))='SB' THEN 'SMART BUSINESS' WHEN UPPER(TRIM(COALESCE(e.company,''))) LIKE '%BRAVOS%' THEN 'BRAVOS' ELSE '__OTHER__' END company,SUM(CASE WHEN ${present} THEN sd.value_num ELSE 0 END) present,SUM(CASE WHEN ${present} THEN 0 ELSE 1 END) absent FROM stage_daily sd JOIN employees e ON e.id=sd.employee_id WHERE ${sq.w} GROUP BY stage,company`).all(...sq.p));const sm=new Map();for(const r of sr){if(!sm.has(r.stage))sm.set(r.stage,{stage:r.stage,companies:{},total:{present:0,absent:0}});const x=sm.get(r.stage);x.companies[r.company]={present:+r.present||0,absent:+r.absent||0};x.total.present+=+r.present||0;x.total.absent+=+r.absent||0}const stage_matrix=[...sm.values()].sort((a,b)=>b.total.absent-a.total.absent||a.stage.localeCompare(b.stage));const stages=stage_matrix.map(r=>({name:r.stage,present:r.total.present,absent:r.total.absent})).sort((a,b)=>(b.present+b.absent)-(a.present+a.absent));
const dq=grouped();const daily=(await db.prepare(`SELECT sd.entry_date date,COUNT(*) total,SUM(CASE WHEN ${present} THEN sd.value_num ELSE 0 END) present,SUM(CASE WHEN ${casual} OR ${permissionCode} OR ${unauth} OR ${medical} THEN 1 ELSE 0 END) absent,SUM(CASE WHEN ${casual} THEN 1 ELSE 0 END) casual,SUM(CASE WHEN ${permissionCode} THEN 1 ELSE 0 END) permission,SUM(CASE WHEN ${unauth} THEN 1 ELSE 0 END) unauthorized,SUM(CASE WHEN ${medical} THEN 1 ELSE 0 END) medical FROM stage_daily sd JOIN employees e ON e.id=sd.employee_id WHERE ${dq.w} GROUP BY sd.entry_date ORDER BY sd.entry_date`).all(...dq.p)).map(r=>{const tt=+r.total||0,pp=+r.present||0;return{...r,total:tt,present:pp,absent:+r.absent||0,casual:+r.casual||0,unauthorized:+r.unauthorized||0,permission:+r.permission||0,medical:+r.medical||0,attendance_rate:tt?pp/tt*100:0,absence_rate:tt?(+r.absent||0)/tt*100:0}});
const eq=grouped();
const employeeRows=(await db.prepare(`SELECT e.id,e.name,e.company,e.shift,e.department,
  SUM(CASE WHEN ${present} THEN sd.value_num ELSE 0 END) present,
  SUM(CASE WHEN ${casual} OR ${permissionCode} OR ${unauth} OR ${medical} THEN 1 ELSE 0 END) absent,
  SUM(CASE WHEN ${casual} THEN 1 ELSE 0 END) casual,
  SUM(CASE WHEN ${permissionCode} THEN 1 ELSE 0 END) permission,
  SUM(CASE WHEN ${unauth} THEN 1 ELSE 0 END) unauthorized,
  SUM(CASE WHEN ${medical} THEN 1 ELSE 0 END) medical,MAX(es.total_present_days) master_present_value,COUNT(*) attendance_days
  FROM stage_daily sd
  JOIN employees e ON e.id=sd.employee_id
  LEFT JOIN employee_summary es ON es.employee_id=e.id
  WHERE ${eq.w}
  GROUP BY e.id,e.name,e.company,e.shift,e.department
  ORDER BY absent DESC,e.name` ).all(...eq.p)).map(r=>{const pp=Number(r.present||0),ab=Number(r.absent||0),tt=Number(r.attendance_days||0);return{...r,present:pp,master_present_bonus:0,master_present_value:r.master_present_value??null,absent:ab,casual:+r.casual||0,permission:+r.permission||0,unauthorized:+r.unauthorized||0,medical:+r.medical||0,attendance_rate:tt?pp/tt*100:0}});
const employees=employeeRows;
// Attendance values 0.5 and 1.5 are real attendance units and are already included in the weighted sums above.
companies.forEach(r=>{
  const tt=Number(r.total||0), pp=Number(r.present||0);
  r.attendance_rate=tt?pp/tt*100:0;
});
stages.forEach(r=>{
  const pp=Number(r.present||0), ab=Number(r.absent||0);
  r.attendance_rate=(pp+ab)?pp/(pp+ab)*100:0;
});
res.json({range:{from,to},totals:{employee_count:employeeCount,total:adjustedTotal,present:adjustedPresent,absent:+t.absent||0,casual:+t.casual||0,permission:+t.permission||0,unauthorized:+t.unauthorized||0,medical:+t.medical||0,attendance_rate:adjustedTotal?adjustedPresent/adjustedTotal*100:0},companies,stages,stage_matrix,daily,employees})});module.exports=router;
