CREATE TABLE IF NOT EXISTS employees (
  id INTEGER PRIMARY KEY,
  emp_num INTEGER,
  name TEXT NOT NULL,
  education TEXT,
  residence TEXT,
  company TEXT,
  shift TEXT,
  target_shift TEXT,
  department TEXT,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'employee',
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_summary (
  employee_id INTEGER PRIMARY KEY REFERENCES employees(id) ON DELETE CASCADE,
  total_achievement DOUBLE PRECISION,
  total_target DOUBLE PRECISION,
  percentage DOUBLE PRECISION,
  bonus_tier TEXT,
  unauthorized_absence DOUBLE PRECISION,
  total_absence DOUBLE PRECISION,
  work_nature_allowance DOUBLE PRECISION,
  monthly_target DOUBLE PRECISION,
  total_present_days DOUBLE PRECISION,
  total_absence_days DOUBLE PRECISION,
  casual_leave DOUBLE PRECISION,
  leave_with_permission DOUBLE PRECISION,
  leave_without_permission DOUBLE PRECISION,
  sick_leave DOUBLE PRECISION,
  late_days DOUBLE PRECISION,
  late_hours DOUBLE PRECISION,
  overtime_days DOUBLE PRECISION,
  overtime_hours DOUBLE PRECISION,
  special_bonus_days DOUBLE PRECISION,
  special_deductions DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS stage_daily (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  entry_date DATE NOT NULL,
  value_num DOUBLE PRECISION,
  value_text TEXT,
  UNIQUE(employee_id, stage, entry_date)
);

CREATE INDEX IF NOT EXISTS idx_stage_daily_emp ON stage_daily(employee_id);
CREATE INDEX IF NOT EXISTS idx_stage_daily_date ON stage_daily(entry_date);
CREATE INDEX IF NOT EXISTS idx_stage_daily_stage ON stage_daily(stage);

CREATE TABLE IF NOT EXISTS supervisor_targets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE,
  supervisor_name TEXT NOT NULL,
  section TEXT NOT NULL,
  entry_date DATE NOT NULL,
  target_daily DOUBLE PRECISION,
  target_monthly DOUBLE PRECISION,
  metrics_json TEXT,
  UNIQUE(section, supervisor_name, entry_date)
);

CREATE INDEX IF NOT EXISTS idx_supervisor_targets_emp ON supervisor_targets(employee_id);
CREATE INDEX IF NOT EXISTS idx_supervisor_targets_date ON supervisor_targets(entry_date);

CREATE TABLE IF NOT EXISTS login_audit (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  success INTEGER NOT NULL,
  ip TEXT,
  ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
