CREATE TABLE IF NOT EXISTS employees (
  id INTEGER PRIMARY KEY,
  emp_num INTEGER,
  name TEXT NOT NULL,
  education TEXT,
  residence TEXT,
  company TEXT,
  shift TEXT,
  target_shift TEXT,
  department TEXT,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'employee',
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  left_date DATE,
  departure_reason TEXT
);

CREATE TABLE IF NOT EXISTS employee_summary (
  employee_id INTEGER PRIMARY KEY REFERENCES employees(id) ON DELETE CASCADE,
  total_achievement DOUBLE PRECISION,
  total_target DOUBLE PRECISION,
  percentage DOUBLE PRECISION,
  bonus_tier TEXT,
  unauthorized_absence DOUBLE PRECISION,
  total_absence DOUBLE PRECISION,
  work_nature_allowance DOUBLE PRECISION,
  monthly_target DOUBLE PRECISION,
  total_present_days DOUBLE PRECISION,
  total_absence_days DOUBLE PRECISION,
  casual_leave DOUBLE PRECISION,
  leave_with_permission DOUBLE PRECISION,
  leave_without_permission DOUBLE PRECISION,
  sick_leave DOUBLE PRECISION,
  late_days DOUBLE PRECISION,
  late_hours DOUBLE PRECISION,
  overtime_days DOUBLE PRECISION,
  overtime_hours DOUBLE PRECISION,
  special_bonus_days DOUBLE PRECISION,
  special_deductions DOUBLE PRECISION
);


-- Monthly snapshot of payroll/target summary. Daily records already retain
-- their exact dates; this table preserves the monthly summary for every month.
CREATE TABLE IF NOT EXISTS employee_monthly_summary (
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  month_start DATE NOT NULL,
  total_achievement DOUBLE PRECISION,
  total_target DOUBLE PRECISION,
  percentage DOUBLE PRECISION,
  bonus_tier TEXT,
  unauthorized_absence DOUBLE PRECISION,
  total_absence DOUBLE PRECISION,
  work_nature_allowance DOUBLE PRECISION,
  monthly_target DOUBLE PRECISION,
  total_present_days DOUBLE PRECISION,
  total_absence_days DOUBLE PRECISION,
  casual_leave DOUBLE PRECISION,
  leave_with_permission DOUBLE PRECISION,
  leave_without_permission DOUBLE PRECISION,
  sick_leave DOUBLE PRECISION,
  late_days DOUBLE PRECISION,
  late_hours DOUBLE PRECISION,
  overtime_days DOUBLE PRECISION,
  overtime_hours DOUBLE PRECISION,
  special_bonus_days DOUBLE PRECISION,
  special_deductions DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (employee_id, month_start)
);
CREATE INDEX IF NOT EXISTS idx_employee_monthly_summary_month ON employee_monthly_summary(month_start);

CREATE TABLE IF NOT EXISTS stage_daily (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  entry_date DATE NOT NULL,
  value_num DOUBLE PRECISION,
  value_text TEXT,
  UNIQUE(employee_id, stage, entry_date)
);

CREATE INDEX IF NOT EXISTS idx_stage_daily_emp ON stage_daily(employee_id);
CREATE INDEX IF NOT EXISTS idx_stage_daily_date ON stage_daily(entry_date);
CREATE INDEX IF NOT EXISTS idx_stage_daily_stage ON stage_daily(stage);

-- Monthly stage targets extracted from the Master!AO formulas during import.
-- Keep the shift and payroll cycle in the key because the same employee can
-- appear in more than one shift and targets may change in a later import.
CREATE TABLE IF NOT EXISTS employee_stage_targets (
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  shift TEXT NOT NULL,
  month_start DATE NOT NULL,
  stage TEXT NOT NULL,
  target_monthly DOUBLE PRECISION NOT NULL,
  source_formula TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (employee_id, shift, month_start, stage)
);
CREATE INDEX IF NOT EXISTS idx_employee_stage_targets_lookup
  ON employee_stage_targets(employee_id, month_start);

CREATE TABLE IF NOT EXISTS supervisor_targets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE,
  supervisor_name TEXT NOT NULL,
  section TEXT NOT NULL,
  entry_date DATE NOT NULL,
  target_daily DOUBLE PRECISION,
  target_monthly DOUBLE PRECISION,
  metrics_json TEXT,
  UNIQUE(section, supervisor_name, entry_date)
);

CREATE INDEX IF NOT EXISTS idx_supervisor_targets_emp ON supervisor_targets(employee_id);
CREATE INDEX IF NOT EXISTS idx_supervisor_targets_date ON supervisor_targets(entry_date);

CREATE TABLE IF NOT EXISTS login_audit (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  success INTEGER NOT NULL,
  ip TEXT,
  ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  actor_name TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details_json JSONB,
  ip TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_id);

CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value_json JSONB NOT NULL,
  updated_by INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_shift_profiles (
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  shift TEXT NOT NULL,
  profile_json JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (employee_id, shift)
);
CREATE INDEX IF NOT EXISTS idx_employee_shift_profiles_emp ON employee_shift_profiles(employee_id);

CREATE TABLE IF NOT EXISTS import_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imported_by INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  imported_by_name TEXT,
  filename TEXT NOT NULL,
  month_start DATE,
  updated_count INTEGER NOT NULL DEFAULT 0,
  created_count INTEGER NOT NULL DEFAULT 0,
  daily_count INTEGER NOT NULL DEFAULT 0,
  skipped_count INTEGER NOT NULL DEFAULT 0,
  supervisor_linked INTEGER NOT NULL DEFAULT 0,
  supervisor_unmatched INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'success',
  details_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_import_history_created_at ON import_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_history_imported_by ON import_history(imported_by);
ALTER TABLE import_history ADD COLUMN IF NOT EXISTS month_start DATE;
CREATE INDEX IF NOT EXISTS idx_import_history_month ON import_history(month_start);

